<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrTile\Tile;

use srag\Plugins\SrTile\Utils\SrTileTrait;
use srag\DIC\SrTile\DICTrait;
use ilSrTilePlugin;

/**
 * Class TileListGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 */
class TileGUI {

	use DICTrait;
	use SrTileTrait;

	const PLUGIN_CLASS_NAME = ilSrTilePlugin::class;
	/**
	 * @var Tile
	 */
	protected $tile;


	/**
	 * TileGUI constructor
	 *
	 * @param int $tile_id
	 */
	public function __construct(int $tile_id) {
		$this->tile = new Tile($tile_id);
	}



	/**
	 * @return string
	 * @throws \ilTemplateException
	 * @throws \srag\DIC\SrTile\Exception\DICException
	 */
	public function render() {
		$tpl =  self::plugin()->template("Tile/tpl.tile.html");
		$tpl->setCurrentBlock("course");
		$tpl->setVariable("LABEL", is_object($this->tile->returnIlObject()) ? $this->tile->returnIlObject()->getTitle() : "");
		$tpl->setVariable("COLOR", "red");
		$tpl->setVariable("LINK", $this->tile->returnLink(), true);
		$tpl->setVariable("IMAGE", $this->tile->returnImagePath(true), true);
		$tpl->parseCurrentBlock();
		return $tpl->get();
	}
}