<?php

namespace srag\Plugins\SrTile\TileList;

use srag\Plugins\SrTile\Tile\TileContainerGUI;

/**
 * Class TileListContainerGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Martin Studer <ms@studer-raimann.ch>
 *
 */
class TileListContainerGUI extends TileListGUIAbstract {

	/**
	 * TileListContainerGUI constructor
	 *
	 * @param int $container_obj_ref_id
	 */
	public function __construct(int $container_obj_ref_id) {
		$this->tile_list = TileListContainer::getInstance($container_obj_ref_id);
	}


	/**
	 * @return string
	 * @throws \ilTemplateException
	 * @throws \srag\DIC\SrTile\Exception\DICException
	 */
	public function getHtml(): string {
		$tile_html = '';
		foreach ($this->tile_list->getTiles() as $tile) {
			$tile_gui = new TileContainerGUI($tile);
			$tile_html .= $tile_gui->render();
		}

		return $tile_html;
	}


	/**
	 * @return void
	 */
	public function hideOriginalRowsOfTiles() /*:void*/ {

		$css = '';
		foreach ($this->tile_list->getTiles() as $tile) {
			$css .= ' #lg_div_';
			$css .= $tile->getObjRefId();
			$css .= '_pref_';
			$css .= $this->tile_list->getContainerObjRefId();
			$css .= '{ display: none !important;} ';
		}

		self::dic()->mainTemplate()->addInlineCss($css);
	}
}