<?php
namespace srag\Plugins\SrTile\TileList;

use function GuzzleHttp\Psr7\parse_header;
use srag\Plugins\SrTile\Utils\SrTileTrait;
use srag\DIC\SrTile\DICTrait;

use ilSrTilePlugin;

/**
 * Class TileListContainerGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Martin Studer <ms@studer-raimann.ch>
 *
 */
class TileListContainerGUI extends TileListGUIAbstract {

	/**
	 * TileListContainerGUI constructor
	 *
	 * @param int $container_obj_ref_id
	 */
	public function __construct(int $container_obj_ref_id) {
		$this->tile_list = TileListContainer::getInstance($container_obj_ref_id);
	}

	/**
	 * @return void
	 */
	public function hideOriginalRowsOfTiles() /*:void*/ {

		$css = '';
		foreach ($this->tile_list->getTiles() as $tile) {
			$css .= ' #lg_div_';
			$css .= $tile->getObjRefId();
			$css .= '_pref_';
			$css .= $this->tile_list->getContainerObjRefId();
			$css .= '{ display: none !important;} ';
		}

		self::dic()->mainTemplate()->addInlineCss($css);
	}

}