<?php
namespace srag\Plugins\SrTile\TileList;


/**
 * Class TileListContainerGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Martin Studer <ms@studer-raimann.ch>
 *
 */
interface TileListGUIInterface {

	/**
	 * @return string
	 * @throws \ilTemplateException
	 * @throws \srag\DIC\SrTile\Exception\DICException
	 */
	public function render();


	/**
	 *
	 * @return string
	 */
	public function getHtml(): string;


	/**
	 * @return void
	 */
	public function hideOriginalRowsOfTiles() /*:void*/;
}