<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\SrTile\Utils\SrTileTrait;
use srag\DIC\SrTile\DICTrait;
use srag\Plugins\SrTile\Tile\TileFormGUI;
use srag\Plugins\SrTile\Tile\Tile;

/**
 * Class SrTileGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrTileGUI: ilUIPluginRouterGUI
 */
class SrTileGUI {

	use DICTrait;
	use SrTileTrait;
	const PLUGIN_CLASS_NAME = ilSrTilePlugin::class;
	const CMD_EDIT_TILE = "editTile";
	const CMD_UPDATE_TILE = "updateTile";
	const LANG_MODULE_TILE = "tile";
	const GET_PARAM_OBJ_REF_ID = 'ref_id';



	/**
	 * SrTileGUI constructor
	 */
	public function __construct() {

	}


	/**
	 *
	 */
	public function executeCommand()/*: void*/ {
		$next_class = self::dic()->ctrl()->getNextClass($this);

		switch (strtolower($next_class)) {
			default:
				$cmd = self::dic()->ctrl()->getCmd();



				switch ($cmd) {
					case self::CMD_EDIT_TILE:
					case self::CMD_UPDATE_TILE:
						$this->{$cmd}();
						break;
					default:
						break;
				}
				break;
		}
	}


	/**
	 * @param Tile $tile
	 *
	 * @return TileFormGUI
	 */
	protected function getTileFormGUI(Tile $tile): TileFormGUI {
		$form = new TileFormGUI($this, $tile);

		return $form;
	}


	/**
	 *
	 */
	protected function editTile()/*: void*/ {


		$tile = Tile::getInstanceForObjRefId(filter_input(INPUT_GET, "ref_id"));
		self::dic()->ctrl()->saveParameterByClass(SrTileGUI::class,self::GET_PARAM_OBJ_REF_ID);


		$form = $this->getTileFormGUI($tile);
		self::plugin()->output($form);
	}


	/**
	 *
	 */
	protected function updateTile()/*: void*/ {

		$tile = Tile::getInstanceForObjRefId(filter_input(INPUT_GET, "ref_id"));
		self::dic()->ctrl()->saveParameterByClass(SrTileGUI::class,self::GET_PARAM_OBJ_REF_ID);

		$form = $this->getTileFormGUI($tile);
		$form->setValuesByPost();

		if (!$form->checkInput()) {
			$this->editTile();
			return;
		}

		$form->updateTile();

		ilUtil::sendSuccess(self::plugin()->translate("saved", self::LANG_MODULE_TILE));

		self::plugin()->output($form);
	}

}