<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrTile\Config;

use srag\Plugins\SrTile\Utils\SrTileTrait;
use ilSrTilePlugin;
use srag\ActiveRecordConfig\SrTile\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @package srag\Plugins\SrTile\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig {

	use SrTileTrait;
	const TABLE_NAME = "ui_uihk_srtile_config";
	const PLUGIN_CLASS_NAME = ilSrTilePlugin::class;
}
