<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrTile\Access;

use ilObjUser;
use ilSrTilePlugin;
use srag\DIC\SrTile\DICTrait;
use srag\Plugins\SrTile\Favorite\Favorites;
use srag\Plugins\SrTile\Utils\SrTileTrait;

/**
 * Class Ilias
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @package srag\Plugins\SrTile\Access
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Ilias {

	use DICTrait;
	use SrTileTrait;
	const PLUGIN_CLASS_NAME = ilSrTilePlugin::class;
	/**
	 * @var self
	 */
	protected static $instance = NULL;


	/**
	 * @return self
	 */
	public static function getInstance(): self {
		if (self::$instance === NULL) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * Ilias constructor
	 */
	private function __construct() {

	}


	/**
	 * @param ilObjUser $user
	 *
	 * @return Favorites
	 */
	public function favorites(ilObjUser $user): Favorites {
		return Favorites::getInstance($user);
	}


	/**
	 * @param ilObjUser $user
	 *
	 * @return LearningProgress
	 */
	public function learningProgress(ilObjUser $user): LearningProgress {
		return LearningProgress::getInstance($user);
	}
}
