<#1>
<?php
\srag\Plugins\SrTile\Tile\Tile::updateDB();
?>
<#2>
<?php
\srag\Plugins\SrTile\Tile\Tile::updateDB();
?>
<#3>
<?php
\srag\Plugins\SrTile\Tile\Tile::updateDB();
?>
<#4>
<?php
\srag\Plugins\SrTile\Tile\Tile::updateDB();
?>
<#5>
<?php
\srag\Plugins\SrTile\Config\Config::updateDB();
?>
<#6>
<?php
\srag\Plugins\SrTile\Tile\Tile::updateDB();
?>
