<?php

namespace srag\Plugins\SrTile\Tile;

/**
 * Class TileListContainerGUI
 *
 * Generated by srag\PluginGenerator v0.9.2
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Martin Studer <ms@studer-raimann.ch>
 *
 */
interface TileGUIInterface {

	/**
	 * @return string
	 * @throws \ilTemplateException
	 * @throws \srag\DIC\SrTile\Exception\DICException
	 */
	public function render();


	/**
	 * @return string
	 */
	public function getActions(): string;


	/**
	 * @return string
	 */
	public function getActionAsyncUrl(): string;


	/**
	 * @return void
	 */
	public function setCardColor() /*:void*/
	;
}